// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1MSSSEdcgLrmQkGpDjhaPV3S91O_hC1Q',
    appId: '1:459346943910:web:398c8eb9db0f978ca5f967',
    messagingSenderId: '459346943910',
    projectId: 'mcx-final',
    authDomain: 'mcx-final.firebaseapp.com',
    storageBucket: 'mcx-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNXcyIZX4zauVe0FS7HKKXafL3USeLPT0',
    appId: '1:459346943910:android:d8538f0d54c9fb77a5f967',
    messagingSenderId: '459346943910',
    projectId: 'mcx-final',
    storageBucket: 'mcx-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIbk4ArHq0vunlOYE7Ybc8sI0mQ-bWVHM',
    appId: '1:459346943910:ios:43ea9ec56b6d6f45a5f967',
    messagingSenderId: '459346943910',
    projectId: 'mcx-final',
    storageBucket: 'mcx-final.appspot.com',
    iosClientId: '459346943910-3kt44ifk8ud3hr7hf6ef7jl3v34ug4ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.sidepanelFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIbk4ArHq0vunlOYE7Ybc8sI0mQ-bWVHM',
    appId: '1:459346943910:ios:f2e77d1086a8d5d6a5f967',
    messagingSenderId: '459346943910',
    projectId: 'mcx-final',
    storageBucket: 'mcx-final.appspot.com',
    iosClientId: '459346943910-gcmisvebno3i5i6o5tr4rbufgfe4h5er.apps.googleusercontent.com',
    iosBundleId: 'com.example.sidepanelFlutter.RunnerTests',
  );
}
